[2025-03-06T15:10:18.374+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-06T15:10:18.388+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_setup_dag.extract_write_raw_weather_data manual__2025-03-06T15:10:14.753236+00:00 [queued]>
[2025-03-06T15:10:18.395+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_setup_dag.extract_write_raw_weather_data manual__2025-03-06T15:10:14.753236+00:00 [queued]>
[2025-03-06T15:10:18.395+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-06T15:10:18.405+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): extract_write_raw_weather_data> on 2025-03-06 15:10:14.753236+00:00
[2025-03-06T15:10:18.412+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=390) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-06T15:10:18.413+0000] {standard_task_runner.py:72} INFO - Started process 392 to run task
[2025-03-06T15:10:18.414+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_setup_dag', 'extract_write_raw_weather_data', 'manual__2025-03-06T15:10:14.753236+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/etl_dag.py', '--cfg-path', '/tmp/tmp_b59lnun']
[2025-03-06T15:10:18.416+0000] {standard_task_runner.py:105} INFO - Job 24: Subtask extract_write_raw_weather_data
[2025-03-06T15:10:18.603+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_setup_dag.extract_write_raw_weather_data manual__2025-03-06T15:10:14.753236+00:00 [running]> on host 4248ae9eea74
[2025-03-06T15:10:18.656+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_setup_dag' AIRFLOW_CTX_TASK_ID='extract_write_raw_weather_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-06T15:10:14.753236+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-06T15:10:14.753236+00:00'
[2025-03-06T15:10:18.657+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-06T15:10:18.667+0000] {logging_mixin.py:190} INFO - Error loading API key: name 'ENV_PATH' is not defined
[2025-03-06T15:10:18.667+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 39, in extract_data
    weather_data = city_weather_data_extraction(CITIES_CONFIG_PATH, ENV_PATH)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/extract.py", line 75, in city_weather_data_extraction
    api_key = load_env_api(ENV_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/extract.py", line 12, in load_env_api
    load_dotenv(ENV_PATH)
                ^^^^^^^^
NameError: name 'ENV_PATH' is not defined. Did you mean: 'ENV_Path'?
[2025-03-06T15:10:18.674+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=etl_setup_dag, task_id=extract_write_raw_weather_data, run_id=manual__2025-03-06T15:10:14.753236+00:00, execution_date=20250306T151014, start_date=20250306T151018, end_date=20250306T151018
[2025-03-06T15:10:18.693+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-06T15:10:18.694+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 24 for task extract_write_raw_weather_data (name 'ENV_PATH' is not defined; 392)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/etl_dag.py", line 39, in extract_data
    weather_data = city_weather_data_extraction(CITIES_CONFIG_PATH, ENV_PATH)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/extract.py", line 75, in city_weather_data_extraction
    api_key = load_env_api(ENV_PATH)
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/extract.py", line 12, in load_env_api
    load_dotenv(ENV_PATH)
                ^^^^^^^^
NameError: name 'ENV_PATH' is not defined. Did you mean: 'ENV_Path'?
[2025-03-06T15:10:18.707+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-06T15:10:18.866+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-06T15:10:18.867+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
